<?php

/*
 * IP Restriction Manager is an open source module developed by SugarCRM, Inc
 * Copyright (C) SugarCRM, Inc.
 *
 * "Upsert® IP Restriction Manager" is an extension to "IP Restriction Manager" developed by Upsert, LLC.
 * Copyright (C) Upsert, LLC.
 *
 * Project: https://github.com/upsertllc/IPRestrictionManager
 * Support: https://github.com/UpsertLLC/IPRestrictionManager/issues
 *
 * Licensed by SugarCRM, Inc under the Apache 2.0 license.
 */

$dictionary['upsert_IPRestrictions'] = [
    'table' => 'upsert_iprestrictions',
    'audited' => true,
    'activity_enabled' => false,
    'acls' => [
        'SugarACLAdminOnly' => true,
        'SugarACLStatic' => false,
    ],
    'duplicate_merge' => true,
    'fields' => [
        'name' => [
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'full_text_search' => [
                'boost' => '3',
                'enabled' => true,
            ],
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'selected',
            'duplicate_on_record_copy' => 'always',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '3',
            'audited' => false,
            'reportable' => false,
            'calculated' => false,
            'size' => '20',
        ],
        'ip_range' => [
            'required' => true,
            'name' => 'ip_range',
            'vname' => 'LBL_IP_RANGE',
            'type' => 'varchar',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'full_text_search' => [
                'boost' => '0',
                'enabled' => false,
            ],
            'calculated' => false,
            'len' => '255',
            'size' => '20',
        ],
        'status' => [
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => true,
            'default' => 'Enabled',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'upsert_iprestrictionmanager_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ],
        'platforms' => [
            'required' => true,
            'name' => 'platforms',
            'vname' => 'LBL_PLATFORMS',
            'type' => 'multienum',
            'massupdate' => true,
            'default' => '^all^',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'options' => '',
            'studio' => 'visible',
            'dependency' => '',
            'isMultiSelect' => true,
        ],

        'upsert_iprestrictions_aclroles' => [
            'name' => 'upsert_iprestrictions_aclroles',
            'type' => 'link',
            'relationship' => 'upsert_iprestrictions_aclroles',
            'source' => 'non-db',
            'module' => 'ACLRoles',
            'bean_name' => 'ACLRole',
            'vname' => 'LBL_UPSERT_IPRESTRICTIONS_ACLROLES_FROM_ACLROLES_TITLE',
            'id_name' => 'upsert_iprestrictions_aclrolesaclroles_idb',
        ],
        'upsert_iprestrictions_teams' => [
            'name' => 'upsert_iprestrictions_teams',
            'type' => 'link',
            'relationship' => 'upsert_iprestrictions_teams',
            'source' => 'non-db',
            'module' => 'Teams',
            'bean_name' => 'Team',
            'side' => 'right',
            'vname' => 'LBL_UPSERT_IPRESTRICTIONS_TEAMS_FROM_UPSERT_IPRESTRICTIONS_TITLE',
            'id_name' => 'upsert_iprestrictions_teamsteams_ida',
            'link-type' => 'one',
        ],
        'upsert_iprestrictions_teams_name' => [
            'name' => 'upsert_iprestrictions_teams_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_UPSERT_IPRESTRICTIONS_TEAMS_FROM_TEAMS_TITLE',
            'save' => true,
            'id_name' => 'upsert_iprestrictions_teamsteams_ida',
            'link' => 'upsert_iprestrictions_teams',
            'table' => 'teams',
            'module' => 'Teams',
            'rname' => 'name',
        ],
        'upsert_iprestrictions_teamsteams_ida' => [
            'name' => 'upsert_iprestrictions_teamsteams_ida',
            'type' => 'id',
            'source' => 'non-db',
            'vname' => 'LBL_UPSERT_IPRESTRICTIONS_TEAMS_FROM_UPSERT_IPRESTRICTIONS_TITLE_ID',
            'id_name' => 'upsert_iprestrictions_teamsteams_ida',
            'link' => 'upsert_iprestrictions_teams',
            'table' => 'teams',
            'module' => 'Teams',
            'rname' => 'id',
            'reportable' => false,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
        ],
        'upsert_iprestrictions_users' => [
            'name' => 'upsert_iprestrictions_users',
            'type' => 'link',
            'relationship' => 'upsert_iprestrictions_users',
            'source' => 'non-db',
            'module' => 'Users',
            'bean_name' => 'User',
            'vname' => 'LBL_UPSERT_IPRESTRICTIONS_USERS_FROM_USERS_TITLE',
            'id_name' => 'upsert_iprestrictions_usersusers_idb',
        ],
    ],
    'relationships' => [],
    'optimistic_locking' => true,
    'unified_search' => false,
    'full_text_search' => false,
];

VardefManager::createVardef('upsert_IPRestrictions', 'upsert_IPRestrictions', ['basic','taggable']);
